
/*
 Filename: RandomGuess.java
 Author: Mikhail Zubko
 Created: 09/15/24
 Purpose: Guess a random number from 1-10 generated by the computer,
 display random number and whether the user won or not.
*/
// TODO: Optional GUI version: import JOptionPane and Random libraries
import javax.swing.JOptionPane;
import java.util.Random;

public class RandomGuess {

  static int ShowMessage(String title, String msg, int opt, int type) {
    return JOptionPane.showConfirmDialog(null, msg, title, opt, type);
  }

  static String play() {
    // TODO: Create constants for random number range, 1 and 11
    // The top number is not included in random number generation
    // It must be 1 number higher
    final int lowNum = 1;
    final int topNum = 11;
    // TODO: Create random number object
    Random rnd = new Random();
    // TODO: Declare variables
    int rndNum;
    int usrNum;
    int chances = 3;
    // TODO: Generate random number from 1-10
    rndNum = rnd.nextInt(lowNum, topNum);
    // TODO: Give to the user a few chances
    while (chances > 0) {
      // TODO: Get number from user
      String input = JOptionPane.showInputDialog(null,
          "Guess my number between 1 and 10\nYou have " + chances + " chances", "Random guess",
          JOptionPane.INFORMATION_MESSAGE);
      if (input == null) {
        return "cancel";
      }
      try {
        usrNum = Integer.parseInt(input);
      } catch (Exception e) {
        continue;
      }
      // TODO: Was the number less than, greater than, or equal to random number
      // Display the results
      // TODO: If the users number was equal to the random number, they win
      chances--;
      if (usrNum == rndNum) {
        return "win";
        // TODO: If the users number was less than the random number, show message
      } else if (usrNum < rndNum) {
        ShowMessage("Miss", "Your number is lower", JOptionPane.DEFAULT_OPTION, 2);
        // TODO: If the users number was greater than the random number, show message
      } else {
        ShowMessage("Miss", "Your number is higher", JOptionPane.DEFAULT_OPTION, 2);
      }
    }
    return "lose";
  }

  public static void main(String[] args) {
    while (true) {
      String result = play();
      if (result == "cancel") {
        break;
      }
      if (result == "lose" && ShowMessage("You lose", "Your game is over.\nPlay again?", 0, 0) == 1) {
        break;
      }
      if (result == "win" && ShowMessage("You win!", "Congratulations!\nPlay again?", 0, 3) == 1) {
        break;
      }
    }
  }
}
